### ISSUE TITLE
Enable SSO Between Azure AD and SAP Cloud Platform Using Identity Authentication Service

### ISSUE THREAD

**Issue by dbh-SAP-githubtest1** [sap-tutorials/btp-foundation#14]
Mission: https://developers.sap.com/mission.cp-azure-ias-single-signon.html
--------------------------

[Register SAP BTP, Cloud Foundry Subaccount in Identity Authentication Service](https://developers.sap.com/tutorials/cp-ias-azure-ad-cf.html)

isn't working it shows me the plain html & the Steps cant be clicked. Tested in Chrome, Edge, Firefox:

![image](https://github.com/sap-tutorials/btp-foundation/assets/113661149/28bd45e0-8173-4452-95c5-bfff00e936b7)

**Comment by dbh-SAP-githubtest1** [comment]
Resolved

**Comment by ValAta** [comment]
Hi @dbh-SAP-githubtest1, 
Thanks for your collaboration. The tutorial works fine now. It seems that this is a general problem and not something specific to that tutorial. If the problem persists. please create a new issue.
BR,
Valentin
