### ISSUE TITLE
Secure a Basic Node.js App with the Authorization and Trust Management Service (XSUAA)

### ISSUE THREAD

**Issue by binsonvarikkasserilabraham** [sap-tutorials/btp-foundation#17]
Tutorials: https://developers.sap.com/tutorials/cp-cf-security-xsuaa-create.html
--------------------------

Write here how you think we can improve the tutorial ...

Under section 3: "Prepare the application security descriptor". Following code snippet is given for xs-security.json... 
  "oauth2-configuration": **[**
    {  
      "redirect-uris": ["https://approuter-product-list-ap25.cfapps.eu10.hana.ondemand.com/login/callback"]          
      }
  **]**

Above code is not correct..  Correct one is the following--- you need to remove the above high lighted [ and ].
    "oauth2-configuration": {
        "redirect-uris": [
            "https://approuter-product-list-ap25.cfapps.eu10.hana.ondemand.com/login/callback"
        ]
    }

**Comment by MichaelPShea** [comment]
@binsonvarikkasserilabraham : Thanks for pointing this out. We will update this example as soon as possible.
