### ISSUE TITLE
Update instructions Step 7, #8 - Create an Application with SAP Java Buildpack

### ISSUE THREAD

**Issue by potatoOnion** [sap-tutorials/btp-foundation#18]
Tutorials: https://developers.sap.com/tutorials/btp-cf-buildpacks-java-create.html
--------------------------

Step 7, #8.  It says "Now you need to apply these changes to the helloworld application by building and redeploying it again."
<img width="515" alt="image" src="https://github.com/sap-tutorials/btp-foundation/assets/9221945/98c1f1c1-7799-416f-8946-a3b817552fc4">

You just need to restart the applications on BTP. No need to rebuild and repush. I've confirmed this myself.

**Comment by Joysie** [comment]
Thank you, @potatoOnion! You might be right! 

I'll go through the tutorial again and update the steps.

Best regards,
Gergana
