### ISSUE TITLE
Create an Application with SAP Java Buildpack

### ISSUE THREAD

**Issue by Made-baka** [sap-tutorials/btp-foundation#2131]
Tutorials: https://developers.sap.com/tutorials/btp-cf-buildpacks-java-create.html
--------------------------
Dear team,

I hope this email finds you well.
I'm writing to discuss about one little issue in the tutorial:
In prerequisites, we are required to install sap machine 11 locally.
However, after following the whole tutorial, when running command :< cf push>, it will fail with error:
ERR java.lang.UnsupportedClassVersionError: org/springframework/boot/loader/launch/JarLauncher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
This is due to the lower version of JDK.

According to this blog:
https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6

I suggested to update to at least SAP Machine 17 to avoid such behavior.

Best regards,
Chris

**Comment by Joysie** [comment]
Hi @Made-baka (Chris),

Thank you for your feedback! Yes, SapMachine 17 is preferable. 

Btw, the tutorial is now updated - consuming the new **SAP Java Buildpack 2** (which makes use of SapMachine JDK 17, Tomcat 10, and Spring Boot 3.x). Feel free to give it a try! 🙂

Same URL:  https://developers.sap.com/tutorials/btp-cf-buildpacks-java-create.html

Best regards,
Gergana
