### ISSUE TITLE
Secure a Basic Node.js App with the Authorization and Trust Management Service (XSUAA)

### ISSUE THREAD

**Issue by gparlakov** [sap-tutorials/btp-foundation#2148]
Tutorials: https://developers.sap.com/tutorials/cp-cf-security-xsuaa-create.html
--------------------------

On the step `Call your application from its secure route` I got a 500 internal error when calling `https://approuter-<my-app-host>.cfapps.<global-account>.hana.ondemand.com/products`.
It turns out there was 1 less binding than required (products-list was bound to the xsuaa service instance but the approuter app was not) 
Fixed following https://me.sap.com/notes/0002949591

**Comment by MichaelPShea** [comment]
@gparlakov: If you had followed the instructions in https://developers.sap.com/tutorials/cp-cf-security-xsuaa-create.html#c88961a3-cc57-49a5-b1a9-5d1de89d1350 step 6, you would have added the binding to the approuter. What we could do is add to the troubleshooting section about the HTTP 500 error message. What do you think?

**Comment by gparlakov** [comment]
Yes adding that to the troubleshooting section sounds great

**Comment by MichaelPShea** [comment]
Updated the troubleshooting with error 500.
