### ISSUE TITLE
Create an Application with Cloud Foundry Python Buildpack

### ISSUE THREAD

**Issue by eexzy** [sap-tutorials/btp-foundation#2152]
Tutorials: https://developers.sap.com/tutorials/btp-cf-buildpacks-python-create.html
--------------------------

Write here how you think we can improve the tutorial ...
I found an error, in Step 4
xs-security.json code provided seems incorrect

It should be
"xsappname" : "pyuaa",

**Comment by Joysie** [comment]
Hi @eexzy ,

Thank you for your comment! 

I can't agree that there's an error though. 
The value of `xsappname` should be the name of an application, not of a service (as what **pyuaa** is).  

You can also check this in the XSA documentation: [Application Security Descriptor Configuration Syntax](https://help.sap.com/docs/SAP_HANA_PLATFORM/4505d0bdaf4948449b7f7379d24d0f0d/6d3ed64092f748cbac691abc5fe52985.html)

Best regards,
Gergana
