### ISSUE TITLE
Create an Application with Cloud Foundry Python Buildpack

### ISSUE THREAD

**Issue by amp86** [sap-tutorials/btp-foundation#34]
Tutorials: https://developers.sap.com/tutorials/btp-cf-buildpacks-python-create.html
--------------------------

hi, I had to replace python-3.11.* with python-3.11.x to make the cf push work. Otherwise it was giving me an error about improper python buildpack constraint.

**Comment by Joysie** [comment]
Hi @amp86,

Thank you for your feedback!

I just tested the app again, using **3.11.*** and **3.11.x** - it worked fine both ways. 

However, according to the official [CF Python documentation](https://docs.cloudfoundry.org/buildpacks/python/index.html#runtime), **3.11.x** is indeed the correct syntax so I'm going to fix my examples accordingly.  Thank you for spotting this little glitch! 🙂

Best regards, Gergana
