### ISSUE TITLE
Secure a Basic Node.js App with the Authorization and Trust Management Service (XSUAA)

### ISSUE THREAD

**Issue by sfdfklskldf** [sap-tutorials/btp-foundation#7]
Tutorials: https://developers.sap.com/tutorials/cp-cf-security-xsuaa-create.html
--------------------------
1) On Step 3 the JSON file is wrong formatted. Especially the part of oauth2-configuration and the redirect url seems also wrong
2) It would be nice to get an informatio non how to run such a secured app locally for further development

**Comment by Prasihub** [comment]
Corrected the formatting and URL
